export const ROUTES = [
    { path: 'home', title: 'Dashboard', icon: 'dashboard', children: null },
    { path: 'profile', title: 'Update Profile', icon: 'person', children: null },
    { path: 'hiring', title: 'Implements and Hiring Details', icon: 'eco', children: null },
    { path: 'sell', title: 'Implements for Sell', icon: 'receipt', children: null },
    { path: 'purchase', title: 'Implements for Purchase', icon: 'add_shopping_cart', children: null },
    { path: 'bookReceive', title: 'Booking Received', icon: 'book', children: null },
    { path: 'bookClosure', title: 'Booking Closure', icon: 'business_center', children: null },
    { path: 'feed', title: 'Feedback & Rating', icon: 'feedback', children: null },
    { path: 'chngPwd', title: 'Change Password', icon: 'vpn_key', children: null },
    { path: 'chngLang', title: 'Change Language', icon: 'g_translate', children: null },
    { path: 'contact', title: 'Contact Us', icon: 'contacts', children: null },
    { path: 'faqs', title: 'FAQs', icon: 'contact_support', children: null },
    { path: 'logout', title: 'Logout', icon: 'exit_to_app', children: null },
]
